#!/bin/bash -e
if [[ ! -f "/home/spark-99310a31-bb23-4591-a094-cc/tmp/uv/uv_0.6.10_linux_arm64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-99310a31-bb23-4591-a094-cc/tmp/uv/uv_0.6.10_linux_arm64" "$@"
